[package]
name = "es-rs-example"
version = "0.1.0"
edition = "2024"

[dependencies]
elasticsearch = "8.5.0-alpha.1"
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
